server:
  port: 8070

spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true

    properties:
      hibernate:
        show_sql: true
        format_sql: true

        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true

    generate-ddl: true
    hibernate:
      ddl-auto: create-drop



  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/community
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/community
#    username: root
#    password: 102030
#    initialization-mode: always # data.sql loding



#logging:
#  level:
#    root: debug

#logging:
#  level:
#    root: error
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
